[rospy.client][INFO] 2017-10-18 07:46:03,267: init_node, name[/state_driving_away], pid[27617]
[xmlrpc][INFO] 2017-10-18 07:46:03,268: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-10-18 07:46:03,269: Started XML-RPC server [http://10.0.0.116:33171/]
[rospy.impl.masterslave][INFO] 2017-10-18 07:46:03,270: _ready: http://10.0.0.116:33171/
[rospy.registration][INFO] 2017-10-18 07:46:03,272: Registering with master node http://10.0.0.116:11311
[xmlrpc][INFO] 2017-10-18 07:46:03,272: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2017-10-18 07:46:03,278: ROS Slave URI: [http://10.0.0.116:33171/]
[rospy.init][INFO] 2017-10-18 07:46:03,278: registered with master
[rospy.rosout][INFO] 2017-10-18 07:46:03,279: initializing /rosout core topic
[rospy.rosout][INFO] 2017-10-18 07:46:03,312: connected to core topic /rosout
[rospy.simtime][INFO] 2017-10-18 07:46:03,321: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-10-18 07:46:03,458: topic[/state_command] adding connection to [http://10.0.0.116:33171/], count 0
[rospy.internal][INFO] 2017-10-18 07:46:03,481: topic[/state_command] adding connection to [/state_driving_away], count 0
[rospy.internal][INFO] 2017-10-18 07:46:03,610: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-10-18 07:46:03,650: topic[/state_command] adding connection to [/state_follow_waypoint], count 1
[rospy.internal][INFO] 2017-10-18 07:46:03,726: topic[/state_command] adding connection to [http://10.0.0.116:40658/], count 1
[rospy.internal][INFO] 2017-10-18 07:46:04,125: topic[/state_command] adding connection to [http://10.0.0.116:37475/], count 2
[rospy.internal][INFO] 2017-10-18 07:46:04,199: topic[/state_command] adding connection to [/state_avoiding_obstacle], count 2
[rospy.internal][INFO] 2017-10-18 07:46:04,241: topic[/state_command] adding connection to [http://10.0.0.116:43499/], count 3
[rospy.internal][INFO] 2017-10-18 07:46:04,305: topic[/state_command] adding connection to [/state_driving_to_cone], count 3
[rospy.internal][INFO] 2017-10-18 07:46:05,417: topic[/mavros/local_position/pose] adding connection to [http://10.0.0.116:35943/], count 0
[rospy.internal][INFO] 2017-10-18 07:46:05,450: topic[/mavros/setpoint_raw/target_local] adding connection to [http://10.0.0.116:35943/], count 0
[rospy.internal][INFO] 2017-10-18 07:46:05,503: topic[/mavros/state] adding connection to [http://10.0.0.116:35943/], count 0
[rospy.internal][INFO] 2017-10-18 07:46:05,571: topic[/mavros/battery] adding connection to [http://10.0.0.116:35943/], count 0
[rospy.internal][INFO] 2017-10-18 07:46:05,574: topic[/mavlink/from] adding connection to [http://10.0.0.116:35943/], count 0
[rospy.internal][INFO] 2017-10-18 07:46:05,952: topic[/mavros/mission/waypoints] adding connection to [http://10.0.0.116:35943/], count 0
[rospy.internal][INFO] 2017-10-18 07:46:06,039: topic[/mavros/rc/override] adding connection to [/mavros], count 0
[rospy.internal][INFO] 2017-10-18 07:46:06,216: topic[/state_command] adding connection to [http://10.0.0.116:34779/], count 4
[rospy.internal][INFO] 2017-10-18 07:46:06,302: topic[/exec_command] adding connection to [/exec], count 0
[rospy.core][INFO] 2017-10-18 07:46:20,560: signal_shutdown [signal-2]
[rospy.internal][ERROR] 2017-10-18 07:46:20,732: Unable to initiate TCP/IP socket to 10.0.0.116:42912 (http://10.0.0.116:40658/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:46:20,739: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-10-18 07:46:20,747: topic[/mavros/rc/override] removing connection to /mavros
[rospy.internal][ERROR] 2017-10-18 07:46:20,741: Unable to initiate TCP/IP socket to 10.0.0.116:39276 (http://10.0.0.116:37475/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-10-18 07:46:20,754: Unable to initiate TCP/IP socket to 10.0.0.116:36615 (http://10.0.0.116:43499/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-10-18 07:46:20,757: Unable to initiate TCP/IP socket to 10.0.0.116:42387 (http://10.0.0.116:34779/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-10-18 07:46:20,764: Unable to initiate TCP/IP socket to 10.0.0.116:33101 (http://10.0.0.116:33171/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:46:20,764: topic[/state_command] removing connection to /state_driving_away
[rospy.internal][INFO] 2017-10-18 07:46:20,767: topic[/state_command] removing connection to /state_follow_waypoint
[rospy.internal][INFO] 2017-10-18 07:46:20,768: topic[/state_command] removing connection to /state_avoiding_obstacle
[rospy.internal][INFO] 2017-10-18 07:46:20,771: topic[/state_command] removing connection to /state_driving_to_cone
[rospy.internal][INFO] 2017-10-18 07:46:20,773: topic[/exec_command] removing connection to /exec
[rospy.internal][INFO] 2017-10-18 07:46:20,780: topic[/mavros/mission/waypoints] removing connection to http://10.0.0.116:35943/
[rospy.internal][INFO] 2017-10-18 07:46:20,781: topic[/mavros/state] removing connection to http://10.0.0.116:35943/
[rospy.internal][INFO] 2017-10-18 07:46:20,786: topic[/mavlink/from] removing connection to http://10.0.0.116:35943/
[rospy.internal][INFO] 2017-10-18 07:46:20,787: topic[/mavros/local_position/pose] removing connection to http://10.0.0.116:35943/
[rospy.internal][WARNING] 2017-10-18 07:46:20,788: Unknown error initiating TCP/IP socket to 10.0.0.116:35884 (http://10.0.0.116:35943/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][INFO] 2017-10-18 07:46:20,794: topic[/mavros/battery] removing connection to http://10.0.0.116:35943/
[rospy.internal][INFO] 2017-10-18 07:46:20,796: topic[/state_command] removing connection to http://10.0.0.116:33171/
[rospy.internal][INFO] 2017-10-18 07:46:20,798: topic[/state_command] removing connection to http://10.0.0.116:40658/
[rospy.internal][INFO] 2017-10-18 07:46:20,799: topic[/state_command] removing connection to http://10.0.0.116:37475/
[rospy.internal][INFO] 2017-10-18 07:46:20,800: topic[/state_command] removing connection to http://10.0.0.116:43499/
[rospy.internal][INFO] 2017-10-18 07:46:20,800: topic[/state_command] removing connection to http://10.0.0.116:34779/
[rospy.internal][INFO] 2017-10-18 07:46:20,801: topic[/mavros/setpoint_raw/target_local] removing connection to http://10.0.0.116:35943/
[rospy.impl.masterslave][INFO] 2017-10-18 07:46:20,802: signal-2
[rospy.core][INFO] 2017-10-18 07:46:21,220: signal_shutdown [atexit]
