[rospy.client][INFO] 2017-10-18 07:48:29,228: init_node, name[/state_avoiding_obstacle], pid[30848]
[xmlrpc][INFO] 2017-10-18 07:48:29,238: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2017-10-18 07:48:29,242: ROS Slave URI: [http://10.0.0.116:43297/]
[xmlrpc][INFO] 2017-10-18 07:48:29,243: Started XML-RPC server [http://10.0.0.116:43297/]
[rospy.impl.masterslave][INFO] 2017-10-18 07:48:29,243: _ready: http://10.0.0.116:43297/
[xmlrpc][INFO] 2017-10-18 07:48:29,244: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-10-18 07:48:29,250: Registering with master node http://10.0.0.116:11311
[rospy.init][INFO] 2017-10-18 07:48:29,343: registered with master
[rospy.rosout][INFO] 2017-10-18 07:48:29,344: initializing /rosout core topic
[rospy.rosout][INFO] 2017-10-18 07:48:29,358: connected to core topic /rosout
[rospy.simtime][INFO] 2017-10-18 07:48:29,379: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-10-18 07:48:29,582: topic[/state_command] adding connection to [http://10.0.0.116:43297/], count 0
[rospy.internal][INFO] 2017-10-18 07:48:29,613: topic[/state_command] adding connection to [/state_avoiding_obstacle], count 0
[rospy.internal][INFO] 2017-10-18 07:48:29,659: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-10-18 07:48:29,905: topic[/state_command] adding connection to [http://10.0.0.116:35502/], count 1
[rospy.internal][INFO] 2017-10-18 07:48:29,966: topic[/state_command] adding connection to [/state_driving_to_cone], count 1
[rospy.internal][INFO] 2017-10-18 07:48:30,133: topic[/state_command] adding connection to [http://10.0.0.116:39812/], count 2
[rospy.internal][INFO] 2017-10-18 07:48:30,163: topic[/state_command] adding connection to [http://10.0.0.116:41980/], count 3
[rospy.internal][INFO] 2017-10-18 07:48:30,180: topic[/state_command] adding connection to [/state_follow_waypoint], count 2
[rospy.internal][INFO] 2017-10-18 07:48:30,258: topic[/state_command] adding connection to [/state_driving_away], count 3
[rospy.internal][INFO] 2017-10-18 07:48:31,352: topic[/mavros/local_position/pose] adding connection to [http://10.0.0.116:37215/], count 0
[rospy.internal][INFO] 2017-10-18 07:48:31,420: topic[/mavros/setpoint_raw/target_local] adding connection to [http://10.0.0.116:37215/], count 0
[rospy.internal][INFO] 2017-10-18 07:48:31,471: topic[/mavros/state] adding connection to [http://10.0.0.116:37215/], count 0
[rospy.internal][INFO] 2017-10-18 07:48:31,477: topic[/mavros/battery] adding connection to [http://10.0.0.116:37215/], count 0
[rospy.internal][INFO] 2017-10-18 07:48:31,558: topic[/mavlink/from] adding connection to [http://10.0.0.116:37215/], count 0
[rospy.internal][INFO] 2017-10-18 07:48:31,991: topic[/mavros/mission/waypoints] adding connection to [http://10.0.0.116:37215/], count 0
[rospy.internal][INFO] 2017-10-18 07:48:32,000: topic[/exec_command] adding connection to [/exec], count 0
[rospy.internal][INFO] 2017-10-18 07:48:32,025: topic[/state_command] adding connection to [http://10.0.0.116:38610/], count 4
[rospy.internal][INFO] 2017-10-18 07:48:32,142: topic[/mavros/rc/override] adding connection to [/mavros], count 0
[rosout][INFO] 2017-10-18 07:48:43,471: /state_avoiding_obstacle MsgId 46 detected. WP item # 7936
[rospy.core][INFO] 2017-10-18 07:48:59,828: signal_shutdown [signal-2]
[rospy.internal][ERROR] 2017-10-18 07:49:00,051: Unable to initiate TCP/IP socket to 10.0.0.116:44721 (http://10.0.0.116:39812/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:49:00,101: topic[/state_command] removing connection to /state_follow_waypoint
[rospy.internal][ERROR] 2017-10-18 07:49:00,181: Unable to initiate TCP/IP socket to 10.0.0.116:39697 (http://10.0.0.116:35502/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-10-18 07:49:00,194: Unable to initiate TCP/IP socket to 10.0.0.116:44738 (http://10.0.0.116:41980/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:49:00,256: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-10-18 07:49:00,257: topic[/mavros/rc/override] removing connection to /mavros
[rospy.internal][INFO] 2017-10-18 07:49:00,259: topic[/state_command] removing connection to /state_avoiding_obstacle
[rospy.internal][ERROR] 2017-10-18 07:49:00,260: Unable to initiate TCP/IP socket to 10.0.0.116:42386 (http://10.0.0.116:43297/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:49:00,262: topic[/state_command] removing connection to /state_driving_to_cone
[rospy.internal][INFO] 2017-10-18 07:49:00,262: topic[/state_command] removing connection to /state_driving_away
[rospy.internal][INFO] 2017-10-18 07:49:00,266: topic[/exec_command] removing connection to /exec
[rospy.internal][INFO] 2017-10-18 07:49:00,269: topic[/mavros/mission/waypoints] removing connection to http://10.0.0.116:37215/
[rospy.internal][INFO] 2017-10-18 07:49:00,283: topic[/mavros/state] removing connection to http://10.0.0.116:37215/
[rospy.internal][INFO] 2017-10-18 07:49:00,286: topic[/mavlink/from] removing connection to http://10.0.0.116:37215/
[rospy.internal][INFO] 2017-10-18 07:49:00,288: topic[/mavros/local_position/pose] removing connection to http://10.0.0.116:37215/
[rospy.internal][WARNING] 2017-10-18 07:49:00,289: Unknown error initiating TCP/IP socket to 10.0.0.116:47667 (http://10.0.0.116:37215/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][INFO] 2017-10-18 07:49:00,290: topic[/mavros/battery] removing connection to http://10.0.0.116:37215/
[rospy.internal][INFO] 2017-10-18 07:49:00,291: topic[/state_command] removing connection to http://10.0.0.116:43297/
[rospy.internal][INFO] 2017-10-18 07:49:00,291: topic[/state_command] removing connection to http://10.0.0.116:35502/
[rospy.internal][INFO] 2017-10-18 07:49:00,292: topic[/state_command] removing connection to http://10.0.0.116:39812/
[rospy.internal][INFO] 2017-10-18 07:49:00,293: topic[/state_command] removing connection to http://10.0.0.116:41980/
[rospy.internal][INFO] 2017-10-18 07:49:00,293: topic[/state_command] removing connection to http://10.0.0.116:38610/
[rospy.internal][INFO] 2017-10-18 07:49:00,295: topic[/mavros/setpoint_raw/target_local] removing connection to http://10.0.0.116:37215/
[rospy.internal][WARNING] 2017-10-18 07:49:00,296: Unknown error initiating TCP/IP socket to 10.0.0.116:47667 (http://10.0.0.116:37215/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.impl.masterslave][INFO] 2017-10-18 07:49:00,297: signal-2
[rospy.core][INFO] 2017-10-18 07:49:00,714: signal_shutdown [atexit]
