[rospy.client][INFO] 2017-10-18 07:48:29,593: init_node, name[/state_driving_to_cone], pid[30818]
[xmlrpc][INFO] 2017-10-18 07:48:29,595: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-10-18 07:48:29,596: Started XML-RPC server [http://10.0.0.116:35502/]
[rospy.impl.masterslave][INFO] 2017-10-18 07:48:29,596: _ready: http://10.0.0.116:35502/
[rospy.init][INFO] 2017-10-18 07:48:29,606: ROS Slave URI: [http://10.0.0.116:35502/]
[rospy.registration][INFO] 2017-10-18 07:48:29,608: Registering with master node http://10.0.0.116:11311
[xmlrpc][INFO] 2017-10-18 07:48:29,609: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2017-10-18 07:48:29,707: registered with master
[rospy.rosout][INFO] 2017-10-18 07:48:29,708: initializing /rosout core topic
[rospy.rosout][INFO] 2017-10-18 07:48:29,739: connected to core topic /rosout
[rospy.simtime][INFO] 2017-10-18 07:48:29,768: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-10-18 07:48:29,908: topic[/state_command] adding connection to [/state_avoiding_obstacle], count 0
[rospy.internal][INFO] 2017-10-18 07:48:29,935: topic[/state_command] adding connection to [http://10.0.0.116:43297/], count 0
[rospy.internal][INFO] 2017-10-18 07:48:29,938: topic[/state_command] adding connection to [http://10.0.0.116:35502/], count 0
[rospy.internal][INFO] 2017-10-18 07:48:29,963: topic[/state_command] adding connection to [/state_driving_to_cone], count 1
[rospy.internal][INFO] 2017-10-18 07:48:29,981: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-10-18 07:48:30,159: topic[/state_command] adding connection to [http://10.0.0.116:39812/], count 2
[rospy.internal][INFO] 2017-10-18 07:48:30,169: topic[/state_command] adding connection to [http://10.0.0.116:41980/], count 3
[rospy.internal][INFO] 2017-10-18 07:48:30,185: topic[/state_command] adding connection to [/state_follow_waypoint], count 2
[rospy.internal][INFO] 2017-10-18 07:48:30,259: topic[/state_command] adding connection to [/state_driving_away], count 3
[rospy.internal][INFO] 2017-10-18 07:48:31,404: topic[/mavros/local_position/pose] adding connection to [http://10.0.0.116:37215/], count 0
[rospy.internal][INFO] 2017-10-18 07:48:31,519: topic[/mavros/setpoint_raw/target_local] adding connection to [http://10.0.0.116:37215/], count 0
[rospy.internal][INFO] 2017-10-18 07:48:31,575: topic[/mavros/battery] adding connection to [http://10.0.0.116:37215/], count 0
[rospy.internal][INFO] 2017-10-18 07:48:31,581: topic[/mavlink/from] adding connection to [http://10.0.0.116:37215/], count 0
[rospy.internal][INFO] 2017-10-18 07:48:31,588: topic[/mavros/state] adding connection to [http://10.0.0.116:37215/], count 0
[rospy.internal][INFO] 2017-10-18 07:48:31,903: topic[/state_command] adding connection to [http://10.0.0.116:38610/], count 4
[rospy.internal][INFO] 2017-10-18 07:48:31,990: topic[/mavros/mission/waypoints] adding connection to [http://10.0.0.116:37215/], count 0
[rospy.internal][INFO] 2017-10-18 07:48:32,023: topic[/exec_command] adding connection to [/exec], count 0
[rospy.internal][INFO] 2017-10-18 07:48:32,117: topic[/mavros/rc/override] adding connection to [/mavros], count 0
[rosout][INFO] 2017-10-18 07:48:43,468: /state_driving_to_cone MsgId 46 detected. WP item # 7936
[rospy.core][INFO] 2017-10-18 07:48:59,856: signal_shutdown [signal-2]
[rospy.internal][ERROR] 2017-10-18 07:49:00,054: Unable to initiate TCP/IP socket to 10.0.0.116:44721 (http://10.0.0.116:39812/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:49:00,172: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-10-18 07:49:00,178: topic[/mavros/rc/override] removing connection to /mavros
[rospy.internal][INFO] 2017-10-18 07:49:00,180: topic[/state_command] removing connection to /state_avoiding_obstacle
[rospy.internal][INFO] 2017-10-18 07:49:00,181: topic[/state_command] removing connection to /state_driving_to_cone
[rospy.internal][INFO] 2017-10-18 07:49:00,183: topic[/state_command] removing connection to /state_follow_waypoint
[rospy.internal][INFO] 2017-10-18 07:49:00,183: topic[/state_command] removing connection to /state_driving_away
[rospy.internal][INFO] 2017-10-18 07:49:00,184: topic[/exec_command] removing connection to /exec
[rospy.internal][INFO] 2017-10-18 07:49:00,188: topic[/mavros/mission/waypoints] removing connection to http://10.0.0.116:37215/
[rospy.internal][INFO] 2017-10-18 07:49:00,192: topic[/mavros/state] removing connection to http://10.0.0.116:37215/
[rospy.internal][WARNING] 2017-10-18 07:49:00,193: Unknown error initiating TCP/IP socket to 10.0.0.116:47667 (http://10.0.0.116:37215/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][ERROR] 2017-10-18 07:49:00,195: Unable to initiate TCP/IP socket to 10.0.0.116:39697 (http://10.0.0.116:35502/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:49:00,198: topic[/mavlink/from] removing connection to http://10.0.0.116:37215/
[rospy.internal][ERROR] 2017-10-18 07:49:00,199: Unable to initiate TCP/IP socket to 10.0.0.116:44738 (http://10.0.0.116:41980/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:49:00,201: topic[/mavros/local_position/pose] removing connection to http://10.0.0.116:37215/
[rospy.internal][INFO] 2017-10-18 07:49:00,202: topic[/mavros/battery] removing connection to http://10.0.0.116:37215/
[rospy.internal][WARNING] 2017-10-18 07:49:00,204: Unknown error initiating TCP/IP socket to 10.0.0.116:47667 (http://10.0.0.116:37215/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][INFO] 2017-10-18 07:49:00,205: topic[/state_command] removing connection to http://10.0.0.116:43297/
[rospy.internal][INFO] 2017-10-18 07:49:00,209: topic[/state_command] removing connection to http://10.0.0.116:35502/
[rospy.internal][INFO] 2017-10-18 07:49:00,210: topic[/state_command] removing connection to http://10.0.0.116:39812/
[rospy.internal][INFO] 2017-10-18 07:49:00,210: topic[/state_command] removing connection to http://10.0.0.116:41980/
[rospy.internal][ERROR] 2017-10-18 07:49:00,212: Unable to initiate TCP/IP socket to 10.0.0.116:45499 (http://10.0.0.116:38610/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:49:00,213: topic[/state_command] removing connection to http://10.0.0.116:38610/
[rospy.topics][ERROR] 2017-10-18 07:49:00,218: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][INFO] 2017-10-18 07:49:00,219: topic[/mavros/setpoint_raw/target_local] removing connection to http://10.0.0.116:37215/
[rospy.impl.masterslave][INFO] 2017-10-18 07:49:00,220: signal-2
[rospy.core][INFO] 2017-10-18 07:49:00,546: signal_shutdown [atexit]
