[rospy.client][INFO] 2017-10-18 07:42:22,706: init_node, name[/state_follow_waypoint], pid[19759]
[xmlrpc][INFO] 2017-10-18 07:42:22,708: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-10-18 07:42:22,710: Started XML-RPC server [http://10.0.0.116:38450/]
[rospy.init][INFO] 2017-10-18 07:42:22,710: ROS Slave URI: [http://10.0.0.116:38450/]
[rospy.impl.masterslave][INFO] 2017-10-18 07:42:22,711: _ready: http://10.0.0.116:38450/
[xmlrpc][INFO] 2017-10-18 07:42:22,713: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-10-18 07:42:22,715: Registering with master node http://10.0.0.116:11311
[rospy.init][INFO] 2017-10-18 07:42:22,811: registered with master
[rospy.rosout][INFO] 2017-10-18 07:42:22,812: initializing /rosout core topic
[rospy.rosout][INFO] 2017-10-18 07:42:22,835: connected to core topic /rosout
[rospy.simtime][INFO] 2017-10-18 07:42:22,861: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-10-18 07:42:23,073: topic[/state_command] adding connection to [/state_avoiding_obstacle], count 0
[rospy.internal][INFO] 2017-10-18 07:42:23,090: topic[/state_command] adding connection to [/state_driving_away], count 1
[rospy.internal][INFO] 2017-10-18 07:42:23,135: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-10-18 07:42:23,150: topic[/state_command] adding connection to [http://10.0.0.116:44415/], count 0
[rospy.internal][INFO] 2017-10-18 07:42:23,167: topic[/state_command] adding connection to [http://10.0.0.116:39068/], count 1
[rospy.internal][INFO] 2017-10-18 07:42:23,187: topic[/state_command] adding connection to [http://10.0.0.116:38450/], count 2
[rospy.internal][INFO] 2017-10-18 07:42:23,204: topic[/state_command] adding connection to [/state_follow_waypoint], count 2
[rospy.internal][INFO] 2017-10-18 07:42:23,225: topic[/state_command] adding connection to [/state_driving_to_cone], count 3
[rospy.internal][INFO] 2017-10-18 07:42:23,260: topic[/state_command] adding connection to [http://10.0.0.116:41037/], count 3
[rospy.internal][INFO] 2017-10-18 07:42:24,227: topic[/mavros/local_position/pose] adding connection to [http://10.0.0.116:38266/], count 0
[rospy.internal][INFO] 2017-10-18 07:42:24,302: topic[/mavros/setpoint_raw/target_local] adding connection to [http://10.0.0.116:38266/], count 0
[rospy.internal][INFO] 2017-10-18 07:42:24,361: topic[/mavros/state] adding connection to [http://10.0.0.116:38266/], count 0
[rospy.internal][INFO] 2017-10-18 07:42:24,406: topic[/mavros/battery] adding connection to [http://10.0.0.116:38266/], count 0
[rospy.internal][INFO] 2017-10-18 07:42:24,411: topic[/mavlink/from] adding connection to [http://10.0.0.116:38266/], count 0
[rospy.internal][INFO] 2017-10-18 07:42:24,668: topic[/mavros/mission/waypoints] adding connection to [http://10.0.0.116:38266/], count 0
[rospy.internal][INFO] 2017-10-18 07:42:24,885: topic[/exec_command] adding connection to [/exec], count 0
[rospy.internal][INFO] 2017-10-18 07:42:24,889: topic[/state_command] adding connection to [http://10.0.0.116:36678/], count 4
[rospy.internal][INFO] 2017-10-18 07:42:24,921: topic[/mavros/rc/override] adding connection to [/mavros], count 0
[rosout][INFO] 2017-10-18 07:42:27,852: /state_follow_waypoint msgid 180 detected
[rospy.core][INFO] 2017-10-18 07:45:05,794: signal_shutdown [signal-2]
[rospy.internal][ERROR] 2017-10-18 07:45:05,977: Unable to initiate TCP/IP socket to 10.0.0.116:42368 (http://10.0.0.116:39068/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:45:06,056: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-10-18 07:45:06,057: topic[/mavros/rc/override] removing connection to /mavros
[rospy.internal][INFO] 2017-10-18 07:45:06,058: topic[/state_command] removing connection to /state_avoiding_obstacle
[rospy.internal][INFO] 2017-10-18 07:45:06,059: topic[/state_command] removing connection to /state_driving_away
[rospy.internal][INFO] 2017-10-18 07:45:06,061: topic[/state_command] removing connection to /state_follow_waypoint
[rospy.internal][INFO] 2017-10-18 07:45:06,063: topic[/state_command] removing connection to /state_driving_to_cone
[rospy.internal][INFO] 2017-10-18 07:45:06,064: topic[/exec_command] removing connection to /exec
[rospy.internal][INFO] 2017-10-18 07:45:06,065: topic[/mavros/mission/waypoints] removing connection to http://10.0.0.116:38266/
[rospy.internal][INFO] 2017-10-18 07:45:06,066: topic[/mavros/state] removing connection to http://10.0.0.116:38266/
[rospy.internal][ERROR] 2017-10-18 07:45:06,068: Unable to initiate TCP/IP socket to 10.0.0.116:39023 (http://10.0.0.116:38450/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:45:06,068: topic[/mavlink/from] removing connection to http://10.0.0.116:38266/
[rospy.internal][WARNING] 2017-10-18 07:45:06,070: Unknown error initiating TCP/IP socket to 10.0.0.116:57813 (http://10.0.0.116:38266/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.topics][ERROR] 2017-10-18 07:45:06,072: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][INFO] 2017-10-18 07:45:06,073: topic[/mavros/local_position/pose] removing connection to http://10.0.0.116:38266/
[rospy.internal][WARNING] 2017-10-18 07:45:06,079: Unknown error initiating TCP/IP socket to 10.0.0.116:57813 (http://10.0.0.116:38266/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][INFO] 2017-10-18 07:45:06,079: topic[/mavros/battery] removing connection to http://10.0.0.116:38266/
[rospy.internal][INFO] 2017-10-18 07:45:06,081: topic[/state_command] removing connection to http://10.0.0.116:44415/
[rospy.internal][INFO] 2017-10-18 07:45:06,081: topic[/state_command] removing connection to http://10.0.0.116:39068/
[rospy.internal][INFO] 2017-10-18 07:45:06,082: topic[/state_command] removing connection to http://10.0.0.116:38450/
[rospy.internal][INFO] 2017-10-18 07:45:06,083: topic[/state_command] removing connection to http://10.0.0.116:41037/
[rospy.internal][INFO] 2017-10-18 07:45:06,091: topic[/state_command] removing connection to http://10.0.0.116:36678/
[rospy.internal][INFO] 2017-10-18 07:45:06,093: topic[/mavros/setpoint_raw/target_local] removing connection to http://10.0.0.116:38266/
[rospy.impl.masterslave][INFO] 2017-10-18 07:45:06,094: signal-2
[rospy.internal][ERROR] 2017-10-18 07:45:06,102: Unable to initiate TCP/IP socket to 10.0.0.116:37647 (http://10.0.0.116:41037/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.core][INFO] 2017-10-18 07:45:06,421: signal_shutdown [atexit]
