[rospy.client][INFO] 2017-10-18 07:42:22,335: init_node, name[/state_avoiding_obstacle], pid[19800]
[xmlrpc][INFO] 2017-10-18 07:42:22,340: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-10-18 07:42:22,341: Started XML-RPC server [http://10.0.0.116:44415/]
[rospy.impl.masterslave][INFO] 2017-10-18 07:42:22,342: _ready: http://10.0.0.116:44415/
[rospy.registration][INFO] 2017-10-18 07:42:22,344: Registering with master node http://10.0.0.116:11311
[rospy.init][INFO] 2017-10-18 07:42:22,345: ROS Slave URI: [http://10.0.0.116:44415/]
[rospy.init][INFO] 2017-10-18 07:42:22,346: registered with master
[rospy.rosout][INFO] 2017-10-18 07:42:22,346: initializing /rosout core topic
[xmlrpc][INFO] 2017-10-18 07:42:22,363: xml rpc node: starting XML-RPC server
[rospy.rosout][INFO] 2017-10-18 07:42:22,368: connected to core topic /rosout
[rospy.simtime][INFO] 2017-10-18 07:42:22,394: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-10-18 07:42:22,582: topic[/state_command] adding connection to [http://10.0.0.116:44415/], count 0
[rospy.internal][INFO] 2017-10-18 07:42:22,621: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-10-18 07:42:22,623: topic[/state_command] adding connection to [/state_avoiding_obstacle], count 0
[rospy.internal][INFO] 2017-10-18 07:42:22,948: topic[/state_command] adding connection to [http://10.0.0.116:39068/], count 1
[rospy.internal][INFO] 2017-10-18 07:42:23,069: topic[/state_command] adding connection to [http://10.0.0.116:38450/], count 2
[rospy.internal][INFO] 2017-10-18 07:42:23,078: topic[/state_command] adding connection to [/state_driving_away], count 1
[rospy.internal][INFO] 2017-10-18 07:42:23,204: topic[/state_command] adding connection to [/state_follow_waypoint], count 2
[rospy.internal][INFO] 2017-10-18 07:42:23,223: topic[/state_command] adding connection to [/state_driving_to_cone], count 3
[rospy.internal][INFO] 2017-10-18 07:42:23,234: topic[/state_command] adding connection to [http://10.0.0.116:41037/], count 3
[rospy.internal][INFO] 2017-10-18 07:42:24,408: topic[/mavros/local_position/pose] adding connection to [http://10.0.0.116:38266/], count 0
[rospy.internal][INFO] 2017-10-18 07:42:24,472: topic[/mavros/state] adding connection to [http://10.0.0.116:38266/], count 0
[rospy.internal][INFO] 2017-10-18 07:42:24,516: topic[/mavros/battery] adding connection to [http://10.0.0.116:38266/], count 0
[rospy.internal][INFO] 2017-10-18 07:42:24,523: topic[/mavlink/from] adding connection to [http://10.0.0.116:38266/], count 0
[rospy.internal][INFO] 2017-10-18 07:42:24,526: topic[/mavros/setpoint_raw/target_local] adding connection to [http://10.0.0.116:38266/], count 0
[rospy.internal][INFO] 2017-10-18 07:42:24,813: topic[/mavros/mission/waypoints] adding connection to [http://10.0.0.116:38266/], count 0
[rospy.internal][INFO] 2017-10-18 07:42:24,873: topic[/state_command] adding connection to [http://10.0.0.116:36678/], count 4
[rospy.internal][INFO] 2017-10-18 07:42:24,902: topic[/exec_command] adding connection to [/exec], count 0
[rospy.internal][INFO] 2017-10-18 07:42:24,935: topic[/mavros/rc/override] adding connection to [/mavros], count 0
[rosout][INFO] 2017-10-18 07:42:27,857: /state_avoiding_obstacle msgid 180 detected
[rospy.core][INFO] 2017-10-18 07:45:05,790: signal_shutdown [signal-2]
[rospy.internal][ERROR] 2017-10-18 07:45:05,975: Unable to initiate TCP/IP socket to 10.0.0.116:42368 (http://10.0.0.116:39068/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-10-18 07:45:06,061: Unable to initiate TCP/IP socket to 10.0.0.116:39023 (http://10.0.0.116:38450/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:45:06,082: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-10-18 07:45:06,082: topic[/mavros/rc/override] removing connection to /mavros
[rospy.internal][INFO] 2017-10-18 07:45:06,083: topic[/state_command] removing connection to /state_avoiding_obstacle
[rospy.internal][ERROR] 2017-10-18 07:45:06,086: Unable to initiate TCP/IP socket to 10.0.0.116:43918 (http://10.0.0.116:44415/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:45:06,091: topic[/state_command] removing connection to /state_driving_away
[rospy.internal][INFO] 2017-10-18 07:45:06,093: topic[/state_command] removing connection to /state_follow_waypoint
[rospy.internal][INFO] 2017-10-18 07:45:06,095: topic[/state_command] removing connection to /state_driving_to_cone
[rospy.internal][INFO] 2017-10-18 07:45:06,096: topic[/exec_command] removing connection to /exec
[rospy.internal][WARNING] 2017-10-18 07:45:06,097: Unknown error initiating TCP/IP socket to 10.0.0.116:57813 (http://10.0.0.116:38266/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][INFO] 2017-10-18 07:45:06,097: topic[/mavros/mission/waypoints] removing connection to http://10.0.0.116:38266/
[rospy.internal][INFO] 2017-10-18 07:45:06,099: topic[/mavros/state] removing connection to http://10.0.0.116:38266/
[rospy.internal][WARNING] 2017-10-18 07:45:06,100: Unknown error initiating TCP/IP socket to 10.0.0.116:57813 (http://10.0.0.116:38266/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][INFO] 2017-10-18 07:45:06,100: topic[/mavlink/from] removing connection to http://10.0.0.116:38266/
[rospy.internal][INFO] 2017-10-18 07:45:06,103: topic[/mavros/local_position/pose] removing connection to http://10.0.0.116:38266/
[rospy.internal][WARNING] 2017-10-18 07:45:06,103: Unknown error initiating TCP/IP socket to 10.0.0.116:57813 (http://10.0.0.116:38266/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][INFO] 2017-10-18 07:45:06,104: topic[/mavros/battery] removing connection to http://10.0.0.116:38266/
[rospy.internal][INFO] 2017-10-18 07:45:06,105: topic[/state_command] removing connection to http://10.0.0.116:44415/
[rospy.internal][INFO] 2017-10-18 07:45:06,107: topic[/state_command] removing connection to http://10.0.0.116:39068/
[rospy.internal][INFO] 2017-10-18 07:45:06,107: topic[/state_command] removing connection to http://10.0.0.116:38450/
[rospy.internal][INFO] 2017-10-18 07:45:06,108: topic[/state_command] removing connection to http://10.0.0.116:41037/
[rospy.internal][INFO] 2017-10-18 07:45:06,109: topic[/state_command] removing connection to http://10.0.0.116:36678/
[rospy.internal][INFO] 2017-10-18 07:45:06,111: topic[/mavros/setpoint_raw/target_local] removing connection to http://10.0.0.116:38266/
[rospy.impl.masterslave][INFO] 2017-10-18 07:45:06,112: signal-2
[rospy.internal][ERROR] 2017-10-18 07:45:06,135: Unable to initiate TCP/IP socket to 10.0.0.116:40050 (http://10.0.0.116:36678/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2017-10-18 07:45:06,136: Unknown error initiating TCP/IP socket to 10.0.0.116:57813 (http://10.0.0.116:38266/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.core][INFO] 2017-10-18 07:45:06,453: signal_shutdown [atexit]
