[rospy.client][INFO] 2017-10-18 07:32:48,898: init_node, name[/state_avoiding_obstacle], pid[5262]
[xmlrpc][INFO] 2017-10-18 07:32:48,906: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2017-10-18 07:32:48,907: ROS Slave URI: [http://10.0.0.116:33147/]
[xmlrpc][INFO] 2017-10-18 07:32:48,908: Started XML-RPC server [http://10.0.0.116:33147/]
[rospy.impl.masterslave][INFO] 2017-10-18 07:32:48,908: _ready: http://10.0.0.116:33147/
[xmlrpc][INFO] 2017-10-18 07:32:48,909: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-10-18 07:32:48,928: Registering with master node http://10.0.0.116:11311
[rospy.init][INFO] 2017-10-18 07:32:49,008: registered with master
[rospy.rosout][INFO] 2017-10-18 07:32:49,009: initializing /rosout core topic
[rospy.rosout][INFO] 2017-10-18 07:32:49,044: connected to core topic /rosout
[rospy.simtime][INFO] 2017-10-18 07:32:49,052: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-10-18 07:32:49,164: topic[/state_command] adding connection to [http://10.0.0.116:33147/], count 0
[rospy.internal][INFO] 2017-10-18 07:32:49,190: topic[/state_command] adding connection to [/state_avoiding_obstacle], count 0
[rospy.internal][INFO] 2017-10-18 07:32:49,338: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-10-18 07:32:49,383: topic[/state_command] adding connection to [http://10.0.0.116:34176/], count 1
[rospy.internal][INFO] 2017-10-18 07:32:49,448: topic[/state_command] adding connection to [/state_driving_away], count 1
[rospy.internal][INFO] 2017-10-18 07:32:49,891: topic[/state_command] adding connection to [http://10.0.0.116:42801/], count 2
[rospy.internal][INFO] 2017-10-18 07:32:49,901: topic[/state_command] adding connection to [/state_driving_to_cone], count 2
[rospy.internal][INFO] 2017-10-18 07:32:49,953: topic[/state_command] adding connection to [http://10.0.0.116:41071/], count 3
[rospy.internal][INFO] 2017-10-18 07:32:50,000: topic[/state_command] adding connection to [/state_follow_waypoint], count 3
[rospy.internal][INFO] 2017-10-18 07:32:50,824: topic[/mavros/setpoint_raw/target_local] adding connection to [http://10.0.0.116:42365/], count 0
[rospy.internal][INFO] 2017-10-18 07:32:50,846: topic[/mavros/state] adding connection to [http://10.0.0.116:42365/], count 0
[rospy.internal][INFO] 2017-10-18 07:32:50,869: topic[/mavros/battery] adding connection to [http://10.0.0.116:42365/], count 0
[rospy.internal][INFO] 2017-10-18 07:32:50,877: topic[/mavlink/from] adding connection to [http://10.0.0.116:42365/], count 0
[rospy.internal][INFO] 2017-10-18 07:32:50,878: topic[/mavros/local_position/pose] adding connection to [http://10.0.0.116:42365/], count 0
[rospy.internal][INFO] 2017-10-18 07:32:51,110: topic[/mavros/mission/waypoints] adding connection to [http://10.0.0.116:42365/], count 0
[rospy.internal][INFO] 2017-10-18 07:32:51,205: topic[/mavros/rc/override] adding connection to [/mavros], count 0
[rospy.internal][INFO] 2017-10-18 07:32:51,356: topic[/exec_command] adding connection to [/exec], count 0
[rospy.internal][INFO] 2017-10-18 07:32:51,437: topic[/state_command] adding connection to [http://10.0.0.116:38599/], count 4
[rospy.core][INFO] 2017-10-18 07:33:29,878: signal_shutdown [signal-2]
[rospy.internal][ERROR] 2017-10-18 07:33:30,085: Unable to initiate TCP/IP socket to 10.0.0.116:36384 (http://10.0.0.116:34176/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:33:30,100: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-10-18 07:33:30,101: topic[/mavros/rc/override] removing connection to /mavros
[rospy.internal][INFO] 2017-10-18 07:33:30,103: topic[/state_command] removing connection to /state_avoiding_obstacle
[rospy.internal][INFO] 2017-10-18 07:33:30,105: topic[/state_command] removing connection to /state_driving_away
[rospy.internal][ERROR] 2017-10-18 07:33:30,106: Unable to initiate TCP/IP socket to 10.0.0.116:38431 (http://10.0.0.116:33147/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:33:30,107: topic[/state_command] removing connection to /state_driving_to_cone
[rospy.internal][INFO] 2017-10-18 07:33:30,108: topic[/state_command] removing connection to /state_follow_waypoint
[rospy.internal][ERROR] 2017-10-18 07:33:30,112: Unable to initiate TCP/IP socket to 10.0.0.116:38642 (http://10.0.0.116:42801/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:33:30,114: topic[/exec_command] removing connection to /exec
[rospy.internal][INFO] 2017-10-18 07:33:30,120: topic[/mavros/mission/waypoints] removing connection to http://10.0.0.116:42365/
[rospy.internal][INFO] 2017-10-18 07:33:30,122: topic[/mavros/state] removing connection to http://10.0.0.116:42365/
[rospy.internal][INFO] 2017-10-18 07:33:30,124: topic[/mavlink/from] removing connection to http://10.0.0.116:42365/
[rospy.internal][INFO] 2017-10-18 07:33:30,130: topic[/mavros/local_position/pose] removing connection to http://10.0.0.116:42365/
[rospy.internal][WARNING] 2017-10-18 07:33:30,131: Unknown error initiating TCP/IP socket to 10.0.0.116:36402 (http://10.0.0.116:42365/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][INFO] 2017-10-18 07:33:30,135: topic[/mavros/battery] removing connection to http://10.0.0.116:42365/
[rospy.internal][WARNING] 2017-10-18 07:33:30,136: Unknown error initiating TCP/IP socket to 10.0.0.116:36402 (http://10.0.0.116:42365/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
AttributeError: 'NoneType' object has no attribute 'connect'

[rospy.internal][INFO] 2017-10-18 07:33:30,137: topic[/state_command] removing connection to http://10.0.0.116:33147/
[rospy.internal][INFO] 2017-10-18 07:33:30,138: topic[/state_command] removing connection to http://10.0.0.116:34176/
[rospy.internal][INFO] 2017-10-18 07:33:30,139: topic[/state_command] removing connection to http://10.0.0.116:42801/
[rospy.internal][INFO] 2017-10-18 07:33:30,139: topic[/state_command] removing connection to http://10.0.0.116:41071/
[rospy.internal][INFO] 2017-10-18 07:33:30,144: topic[/state_command] removing connection to http://10.0.0.116:38599/
[rospy.internal][INFO] 2017-10-18 07:33:30,146: topic[/mavros/setpoint_raw/target_local] removing connection to http://10.0.0.116:42365/
[rospy.impl.masterslave][INFO] 2017-10-18 07:33:30,147: signal-2
[rospy.internal][ERROR] 2017-10-18 07:33:30,146: Unable to initiate TCP/IP socket to 10.0.0.116:44772 (http://10.0.0.116:38599/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2017-10-18 07:33:30,152: Unknown error initiating TCP/IP socket to 10.0.0.116:36402 (http://10.0.0.116:42365/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.core][INFO] 2017-10-18 07:33:30,534: signal_shutdown [atexit]
