[rospy.client][INFO] 2017-10-02 12:54:42,162: init_node, name[/state_driving_to_cone], pid[6409]
[xmlrpc][INFO] 2017-10-02 12:54:42,163: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-10-02 12:54:42,165: Started XML-RPC server [http://10.0.0.116:44767/]
[rospy.impl.masterslave][INFO] 2017-10-02 12:54:42,166: _ready: http://10.0.0.116:44767/
[rospy.init][INFO] 2017-10-02 12:54:42,165: ROS Slave URI: [http://10.0.0.116:44767/]
[xmlrpc][INFO] 2017-10-02 12:54:42,167: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-10-02 12:54:42,169: Registering with master node http://10.0.0.116:11311
[rospy.init][INFO] 2017-10-02 12:54:42,267: registered with master
[rospy.rosout][INFO] 2017-10-02 12:54:42,268: initializing /rosout core topic
[rospy.rosout][INFO] 2017-10-02 12:54:42,301: connected to core topic /rosout
[rospy.simtime][INFO] 2017-10-02 12:54:42,311: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-10-02 12:54:42,426: topic[/state_command] adding connection to [/state_avoiding_obstacle], count 0
[rospy.core][INFO] 2017-10-02 12:54:42,427: signal_shutdown [signal-2]
[rospy.internal][INFO] 2017-10-02 12:54:42,447: topic[/state_command] adding connection to [http://10.0.0.116:44619/], count 0
[rospy.internal][INFO] 2017-10-02 12:54:42,449: topic[/state_command] adding connection to [http://10.0.0.116:37656/], count 0
[rospy.internal][INFO] 2017-10-02 12:54:42,463: topic[/state_command] adding connection to [http://10.0.0.116:45876/], count 2
[rospy.internal][INFO] 2017-10-02 12:54:42,470: topic[/state_command] adding connection to [http://10.0.0.116:44767/], count 3
[rospy.internal][ERROR] 2017-10-02 12:54:42,523: Unable to initiate TCP/IP socket to 10.0.0.116:34017 (http://10.0.0.116:44619/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-10-02 12:54:42,523: unable to create subscriber transport: remote error reported: node shutting down.  Will try again in 0.5s
[rospy.internal][ERROR] 2017-10-02 12:54:42,525: Unable to initiate TCP/IP socket to 10.0.0.116:36310 (http://10.0.0.116:45876/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-10-02 12:54:42,526: unable to create subscriber transport: remote error reported: node shutting down.  Will try again in 0.5s
[rospy.internal][ERROR] 2017-10-02 12:54:42,527: Unable to initiate TCP/IP socket to 10.0.0.116:41536 (http://10.0.0.116:37656/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-10-02 12:54:42,528: unable to create subscriber transport: remote error reported: node shutting down.  Will try again in 0.5s
[rospy.internal][ERROR] 2017-10-02 12:54:42,529: Unable to initiate TCP/IP socket to 10.0.0.116:35748 (http://10.0.0.116:44767/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-10-02 12:54:42,529: unable to create subscriber transport: remote error reported: node shutting down.  Will try again in 0.5s
[rospy.internal][INFO] 2017-10-02 12:54:42,607: topic[/state_command] removing connection to /state_avoiding_obstacle
[rospy.internal][INFO] 2017-10-02 12:54:42,608: topic[/state_command] removing connection to http://10.0.0.116:44619/
[rospy.internal][INFO] 2017-10-02 12:54:42,609: topic[/state_command] removing connection to http://10.0.0.116:37656/
[rospy.internal][INFO] 2017-10-02 12:54:42,610: topic[/state_command] removing connection to http://10.0.0.116:45876/
[rospy.internal][INFO] 2017-10-02 12:54:42,610: topic[/state_command] removing connection to http://10.0.0.116:44767/
[rospy.impl.masterslave][INFO] 2017-10-02 12:54:42,611: signal-2
[rospy.core][INFO] 2017-10-02 12:54:43,388: signal_shutdown [atexit]
