[rospy.client][INFO] 2017-10-18 07:50:21,409: init_node, name[/state_avoiding_obstacle], pid[5143]
[xmlrpc][INFO] 2017-10-18 07:50:21,411: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-10-18 07:50:21,412: Started XML-RPC server [http://10.0.0.116:38324/]
[rospy.impl.masterslave][INFO] 2017-10-18 07:50:21,420: _ready: http://10.0.0.116:38324/
[rospy.init][INFO] 2017-10-18 07:50:21,421: ROS Slave URI: [http://10.0.0.116:38324/]
[rospy.registration][INFO] 2017-10-18 07:50:21,424: Registering with master node http://10.0.0.116:11311
[xmlrpc][INFO] 2017-10-18 07:50:21,425: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2017-10-18 07:50:21,522: registered with master
[rospy.rosout][INFO] 2017-10-18 07:50:21,523: initializing /rosout core topic
[rospy.rosout][INFO] 2017-10-18 07:50:21,532: connected to core topic /rosout
[rospy.simtime][INFO] 2017-10-18 07:50:21,539: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-10-18 07:50:21,603: topic[/state_command] adding connection to [http://10.0.0.116:40494/], count 0
[rospy.internal][INFO] 2017-10-18 07:50:21,607: topic[/state_command] adding connection to [http://10.0.0.116:38297/], count 0
[rospy.internal][INFO] 2017-10-18 07:50:21,614: topic[/state_command] adding connection to [http://10.0.0.116:42757/], count 1
[rospy.internal][INFO] 2017-10-18 07:50:21,622: topic[/state_command] adding connection to [http://10.0.0.116:38324/], count 1
[rospy.internal][INFO] 2017-10-18 07:50:21,632: topic[/state_command] adding connection to [/state_avoiding_obstacle], count 0
[rospy.internal][INFO] 2017-10-18 07:50:21,692: topic[/state_command] adding connection to [/state_follow_waypoint], count 1
[rospy.internal][INFO] 2017-10-18 07:50:21,694: topic[/state_command] adding connection to [/state_driving_to_cone], count 2
[rospy.internal][INFO] 2017-10-18 07:50:21,696: topic[/state_command] adding connection to [/state_driving_away], count 3
[rospy.internal][INFO] 2017-10-18 07:50:21,751: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-10-18 07:50:21,986: topic[/mavros/local_position/pose] adding connection to [http://10.0.0.116:45828/], count 0
[rospy.internal][INFO] 2017-10-18 07:50:22,012: topic[/mavros/state] adding connection to [http://10.0.0.116:45828/], count 0
[rospy.internal][INFO] 2017-10-18 07:50:22,058: topic[/mavros/battery] adding connection to [http://10.0.0.116:45828/], count 0
[rospy.internal][INFO] 2017-10-18 07:50:22,060: topic[/mavros/setpoint_raw/target_local] adding connection to [http://10.0.0.116:45828/], count 0
[rospy.internal][INFO] 2017-10-18 07:50:22,062: topic[/mavlink/from] adding connection to [http://10.0.0.116:45828/], count 0
[rospy.internal][INFO] 2017-10-18 07:50:22,316: topic[/mavros/mission/waypoints] adding connection to [http://10.0.0.116:45828/], count 0
[rospy.internal][INFO] 2017-10-18 07:50:22,446: topic[/mavros/rc/override] adding connection to [/mavros], count 0
[rospy.internal][INFO] 2017-10-18 07:50:22,542: topic[/state_command] adding connection to [http://10.0.0.116:42545/], count 4
[rospy.internal][INFO] 2017-10-18 07:50:22,623: topic[/exec_command] adding connection to [/exec], count 0
[rospy.core][INFO] 2017-10-18 07:51:05,700: signal_shutdown [signal-2]
[rospy.internal][ERROR] 2017-10-18 07:51:06,051: Unable to initiate TCP/IP socket to 10.0.0.116:42659 (http://10.0.0.116:42757/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-10-18 07:51:06,108: Unable to initiate TCP/IP socket to 10.0.0.116:38031 (http://10.0.0.116:38297/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:51:06,139: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-10-18 07:51:06,143: topic[/mavros/rc/override] removing connection to /mavros
[rospy.internal][INFO] 2017-10-18 07:51:06,144: topic[/state_command] removing connection to /state_avoiding_obstacle
[rospy.internal][INFO] 2017-10-18 07:51:06,147: topic[/state_command] removing connection to /state_follow_waypoint
[rospy.internal][ERROR] 2017-10-18 07:51:06,148: Unable to initiate TCP/IP socket to 10.0.0.116:33133 (http://10.0.0.116:38324/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:51:06,150: topic[/state_command] removing connection to /state_driving_to_cone
[rospy.internal][INFO] 2017-10-18 07:51:06,151: topic[/state_command] removing connection to /state_driving_away
[rospy.internal][INFO] 2017-10-18 07:51:06,152: topic[/exec_command] removing connection to /exec
[rospy.internal][INFO] 2017-10-18 07:51:06,153: topic[/mavros/mission/waypoints] removing connection to http://10.0.0.116:45828/
[rospy.internal][INFO] 2017-10-18 07:51:06,154: topic[/mavros/state] removing connection to http://10.0.0.116:45828/
[rospy.internal][INFO] 2017-10-18 07:51:06,156: topic[/mavlink/from] removing connection to http://10.0.0.116:45828/
[rospy.internal][INFO] 2017-10-18 07:51:06,157: topic[/mavros/local_position/pose] removing connection to http://10.0.0.116:45828/
[rospy.topics][ERROR] 2017-10-18 07:51:06,175: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][WARNING] 2017-10-18 07:51:06,179: Unknown error initiating TCP/IP socket to 10.0.0.116:59484 (http://10.0.0.116:45828/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][INFO] 2017-10-18 07:51:06,182: topic[/mavros/battery] removing connection to http://10.0.0.116:45828/
[rospy.internal][INFO] 2017-10-18 07:51:06,183: topic[/state_command] removing connection to http://10.0.0.116:40494/
[rospy.internal][WARNING] 2017-10-18 07:51:06,191: Unknown error initiating TCP/IP socket to 10.0.0.116:59484 (http://10.0.0.116:45828/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][INFO] 2017-10-18 07:51:06,206: topic[/state_command] removing connection to http://10.0.0.116:38297/
[rospy.internal][INFO] 2017-10-18 07:51:06,207: topic[/state_command] removing connection to http://10.0.0.116:42757/
[rospy.internal][INFO] 2017-10-18 07:51:06,208: topic[/state_command] removing connection to http://10.0.0.116:38324/
[rospy.internal][INFO] 2017-10-18 07:51:06,216: topic[/state_command] removing connection to http://10.0.0.116:42545/
[rospy.internal][INFO] 2017-10-18 07:51:06,217: topic[/mavros/setpoint_raw/target_local] removing connection to http://10.0.0.116:45828/
[rospy.impl.masterslave][INFO] 2017-10-18 07:51:06,218: signal-2
[rospy.internal][WARNING] 2017-10-18 07:51:06,254: Unknown error initiating TCP/IP socket to 10.0.0.116:42504 (http://10.0.0.116:42545/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.core][INFO] 2017-10-18 07:51:06,328: signal_shutdown [atexit]
