[rospy.client][INFO] 2017-10-18 07:50:20,336: init_node, name[/state_follow_waypoint], pid[5094]
[xmlrpc][INFO] 2017-10-18 07:50:20,337: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2017-10-18 07:50:20,344: ROS Slave URI: [http://10.0.0.116:38297/]
[xmlrpc][INFO] 2017-10-18 07:50:20,345: Started XML-RPC server [http://10.0.0.116:38297/]
[rospy.impl.masterslave][INFO] 2017-10-18 07:50:20,345: _ready: http://10.0.0.116:38297/
[xmlrpc][INFO] 2017-10-18 07:50:20,358: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-10-18 07:50:20,361: Registering with master node http://10.0.0.116:11311
[rospy.init][INFO] 2017-10-18 07:50:20,445: registered with master
[rospy.rosout][INFO] 2017-10-18 07:50:20,446: initializing /rosout core topic
[rospy.rosout][INFO] 2017-10-18 07:50:20,460: connected to core topic /rosout
[rospy.simtime][INFO] 2017-10-18 07:50:20,483: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-10-18 07:50:20,647: topic[/state_command] adding connection to [http://10.0.0.116:38297/], count 0
[rospy.internal][INFO] 2017-10-18 07:50:20,669: topic[/state_command] adding connection to [/state_follow_waypoint], count 0
[rospy.internal][INFO] 2017-10-18 07:50:20,677: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-10-18 07:50:21,147: topic[/state_command] adding connection to [http://10.0.0.116:40494/], count 1
[rospy.internal][INFO] 2017-10-18 07:50:21,170: topic[/state_command] adding connection to [/state_driving_to_cone], count 1
[rospy.internal][INFO] 2017-10-18 07:50:21,367: topic[/state_command] adding connection to [http://10.0.0.116:42757/], count 2
[rospy.internal][INFO] 2017-10-18 07:50:21,434: topic[/state_command] adding connection to [/state_driving_away], count 2
[rospy.internal][INFO] 2017-10-18 07:50:21,628: topic[/state_command] adding connection to [/state_avoiding_obstacle], count 3
[rospy.internal][INFO] 2017-10-18 07:50:21,687: topic[/state_command] adding connection to [http://10.0.0.116:38324/], count 3
[rospy.internal][INFO] 2017-10-18 07:50:22,037: topic[/mavros/setpoint_raw/target_local] adding connection to [http://10.0.0.116:45828/], count 0
[rospy.internal][INFO] 2017-10-18 07:50:22,084: topic[/mavros/state] adding connection to [http://10.0.0.116:45828/], count 0
[rospy.internal][INFO] 2017-10-18 07:50:22,127: topic[/mavros/battery] adding connection to [http://10.0.0.116:45828/], count 0
[rospy.internal][INFO] 2017-10-18 07:50:22,132: topic[/mavros/local_position/pose] adding connection to [http://10.0.0.116:45828/], count 0
[rospy.internal][INFO] 2017-10-18 07:50:22,136: topic[/mavlink/from] adding connection to [http://10.0.0.116:45828/], count 0
[rospy.internal][INFO] 2017-10-18 07:50:22,406: topic[/mavros/mission/waypoints] adding connection to [http://10.0.0.116:45828/], count 0
[rospy.internal][INFO] 2017-10-18 07:50:22,505: topic[/state_command] adding connection to [http://10.0.0.116:42545/], count 4
[rospy.internal][INFO] 2017-10-18 07:50:22,566: topic[/mavros/rc/override] adding connection to [/mavros], count 0
[rospy.internal][INFO] 2017-10-18 07:50:22,599: topic[/exec_command] adding connection to [/exec], count 0
[rospy.core][INFO] 2017-10-18 07:51:05,752: signal_shutdown [signal-2]
[rospy.internal][ERROR] 2017-10-18 07:51:06,040: Unable to initiate TCP/IP socket to 10.0.0.116:42659 (http://10.0.0.116:42757/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:51:06,093: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-10-18 07:51:06,095: topic[/mavros/rc/override] removing connection to /mavros
[rospy.internal][INFO] 2017-10-18 07:51:06,096: topic[/state_command] removing connection to /state_follow_waypoint
[rospy.internal][INFO] 2017-10-18 07:51:06,097: topic[/state_command] removing connection to /state_driving_to_cone
[rospy.internal][INFO] 2017-10-18 07:51:06,100: topic[/state_command] removing connection to /state_driving_away
[rospy.internal][INFO] 2017-10-18 07:51:06,101: topic[/state_command] removing connection to /state_avoiding_obstacle
[rospy.internal][INFO] 2017-10-18 07:51:06,102: topic[/exec_command] removing connection to /exec
[rospy.internal][INFO] 2017-10-18 07:51:06,105: topic[/mavros/mission/waypoints] removing connection to http://10.0.0.116:45828/
[rospy.internal][WARNING] 2017-10-18 07:51:06,107: Unknown error initiating TCP/IP socket to 10.0.0.116:59484 (http://10.0.0.116:45828/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][ERROR] 2017-10-18 07:51:06,108: Unable to initiate TCP/IP socket to 10.0.0.116:38031 (http://10.0.0.116:38297/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.topics][ERROR] 2017-10-18 07:51:06,110: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][INFO] 2017-10-18 07:51:06,113: topic[/mavros/state] removing connection to http://10.0.0.116:45828/
[rospy.internal][INFO] 2017-10-18 07:51:06,114: topic[/mavlink/from] removing connection to http://10.0.0.116:45828/
[rospy.topics][ERROR] 2017-10-18 07:51:06,116: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][WARNING] 2017-10-18 07:51:06,117: Unknown error initiating TCP/IP socket to 10.0.0.116:59484 (http://10.0.0.116:45828/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][INFO] 2017-10-18 07:51:06,118: topic[/mavros/local_position/pose] removing connection to http://10.0.0.116:45828/
[rospy.internal][WARNING] 2017-10-18 07:51:06,119: Unknown error initiating TCP/IP socket to 10.0.0.116:59484 (http://10.0.0.116:45828/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.topics][ERROR] 2017-10-18 07:51:06,120: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][INFO] 2017-10-18 07:51:06,122: topic[/mavros/battery] removing connection to http://10.0.0.116:45828/
[rospy.internal][WARNING] 2017-10-18 07:51:06,124: Unknown error initiating TCP/IP socket to 10.0.0.116:59484 (http://10.0.0.116:45828/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.topics][ERROR] 2017-10-18 07:51:06,126: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][INFO] 2017-10-18 07:51:06,126: topic[/state_command] removing connection to http://10.0.0.116:38297/
[rospy.internal][INFO] 2017-10-18 07:51:06,127: topic[/state_command] removing connection to http://10.0.0.116:40494/
[rospy.internal][INFO] 2017-10-18 07:51:06,128: topic[/state_command] removing connection to http://10.0.0.116:42757/
[rospy.internal][INFO] 2017-10-18 07:51:06,128: topic[/state_command] removing connection to http://10.0.0.116:38324/
[rospy.internal][INFO] 2017-10-18 07:51:06,130: topic[/state_command] removing connection to http://10.0.0.116:42545/
[rospy.internal][WARNING] 2017-10-18 07:51:06,131: Unknown error initiating TCP/IP socket to 10.0.0.116:42504 (http://10.0.0.116:42545/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.topics][ERROR] 2017-10-18 07:51:06,133: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][INFO] 2017-10-18 07:51:06,141: topic[/mavros/setpoint_raw/target_local] removing connection to http://10.0.0.116:45828/
[rospy.impl.masterslave][INFO] 2017-10-18 07:51:06,143: signal-2
[rospy.core][INFO] 2017-10-18 07:51:06,250: signal_shutdown [atexit]
