[rospy.client][INFO] 2017-10-18 07:50:20,886: init_node, name[/state_driving_to_cone], pid[5103]
[xmlrpc][INFO] 2017-10-18 07:50:20,895: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-10-18 07:50:20,897: Started XML-RPC server [http://10.0.0.116:40494/]
[rospy.impl.masterslave][INFO] 2017-10-18 07:50:20,898: _ready: http://10.0.0.116:40494/
[rospy.registration][INFO] 2017-10-18 07:50:20,901: Registering with master node http://10.0.0.116:11311
[xmlrpc][INFO] 2017-10-18 07:50:20,901: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2017-10-18 07:50:20,897: ROS Slave URI: [http://10.0.0.116:40494/]
[rospy.init][INFO] 2017-10-18 07:50:20,905: registered with master
[rospy.rosout][INFO] 2017-10-18 07:50:20,906: initializing /rosout core topic
[rospy.rosout][INFO] 2017-10-18 07:50:20,925: connected to core topic /rosout
[rospy.simtime][INFO] 2017-10-18 07:50:20,937: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-10-18 07:50:21,141: topic[/state_command] adding connection to [http://10.0.0.116:40494/], count 0
[rospy.internal][INFO] 2017-10-18 07:50:21,147: topic[/state_command] adding connection to [http://10.0.0.116:38297/], count 1
[rospy.internal][INFO] 2017-10-18 07:50:21,152: topic[/state_command] adding connection to [/state_follow_waypoint], count 0
[rospy.internal][INFO] 2017-10-18 07:50:21,175: topic[/state_command] adding connection to [/state_driving_to_cone], count 1
[rospy.internal][INFO] 2017-10-18 07:50:21,216: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-10-18 07:50:21,376: topic[/state_command] adding connection to [http://10.0.0.116:42757/], count 2
[rospy.internal][INFO] 2017-10-18 07:50:21,430: topic[/state_command] adding connection to [/state_driving_away], count 2
[rospy.internal][INFO] 2017-10-18 07:50:21,622: topic[/state_command] adding connection to [/state_avoiding_obstacle], count 3
[rospy.internal][INFO] 2017-10-18 07:50:21,692: topic[/state_command] adding connection to [http://10.0.0.116:38324/], count 3
[rospy.internal][INFO] 2017-10-18 07:50:22,180: topic[/mavros/local_position/pose] adding connection to [http://10.0.0.116:45828/], count 0
[rospy.internal][INFO] 2017-10-18 07:50:22,227: topic[/mavros/state] adding connection to [http://10.0.0.116:45828/], count 0
[rospy.internal][INFO] 2017-10-18 07:50:22,229: topic[/mavros/setpoint_raw/target_local] adding connection to [http://10.0.0.116:45828/], count 0
[rospy.internal][INFO] 2017-10-18 07:50:22,336: topic[/mavros/battery] adding connection to [http://10.0.0.116:45828/], count 0
[rospy.internal][INFO] 2017-10-18 07:50:22,352: topic[/mavlink/from] adding connection to [http://10.0.0.116:45828/], count 0
[rospy.internal][INFO] 2017-10-18 07:50:22,540: topic[/state_command] adding connection to [http://10.0.0.116:42545/], count 4
[rospy.internal][INFO] 2017-10-18 07:50:22,571: topic[/mavros/mission/waypoints] adding connection to [http://10.0.0.116:45828/], count 0
[rospy.internal][INFO] 2017-10-18 07:50:22,605: topic[/exec_command] adding connection to [/exec], count 0
[rospy.internal][INFO] 2017-10-18 07:50:22,685: topic[/mavros/rc/override] adding connection to [/mavros], count 0
[rospy.core][INFO] 2017-10-18 07:51:05,741: signal_shutdown [signal-2]
[rospy.internal][ERROR] 2017-10-18 07:51:06,045: Unable to initiate TCP/IP socket to 10.0.0.116:42659 (http://10.0.0.116:42757/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:51:06,098: topic[/state_command] removing connection to /state_driving_away
[rospy.internal][ERROR] 2017-10-18 07:51:06,101: Unable to initiate TCP/IP socket to 10.0.0.116:38031 (http://10.0.0.116:38297/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-10-18 07:51:06,150: Unable to initiate TCP/IP socket to 10.0.0.116:33133 (http://10.0.0.116:38324/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:51:06,199: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-10-18 07:51:06,208: topic[/mavros/rc/override] removing connection to /mavros
[rospy.internal][INFO] 2017-10-18 07:51:06,210: topic[/state_command] removing connection to /state_follow_waypoint
[rospy.internal][INFO] 2017-10-18 07:51:06,211: topic[/state_command] removing connection to /state_driving_to_cone
[rospy.internal][ERROR] 2017-10-18 07:51:06,213: Unable to initiate TCP/IP socket to 10.0.0.116:41624 (http://10.0.0.116:40494/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:51:06,222: topic[/state_command] removing connection to /state_avoiding_obstacle
[rospy.internal][INFO] 2017-10-18 07:51:06,223: topic[/exec_command] removing connection to /exec
[rospy.internal][INFO] 2017-10-18 07:51:06,224: topic[/mavros/mission/waypoints] removing connection to http://10.0.0.116:45828/
[rospy.internal][INFO] 2017-10-18 07:51:06,225: topic[/mavros/state] removing connection to http://10.0.0.116:45828/
[rospy.internal][INFO] 2017-10-18 07:51:06,226: topic[/mavlink/from] removing connection to http://10.0.0.116:45828/
[rospy.internal][INFO] 2017-10-18 07:51:06,227: topic[/mavros/local_position/pose] removing connection to http://10.0.0.116:45828/
[rospy.internal][INFO] 2017-10-18 07:51:06,228: topic[/mavros/battery] removing connection to http://10.0.0.116:45828/
[rospy.internal][INFO] 2017-10-18 07:51:06,229: topic[/state_command] removing connection to http://10.0.0.116:40494/
[rospy.internal][INFO] 2017-10-18 07:51:06,231: topic[/state_command] removing connection to http://10.0.0.116:38297/
[rospy.internal][INFO] 2017-10-18 07:51:06,232: topic[/state_command] removing connection to http://10.0.0.116:42757/
[rospy.internal][INFO] 2017-10-18 07:51:06,232: topic[/state_command] removing connection to http://10.0.0.116:38324/
[rospy.internal][WARNING] 2017-10-18 07:51:06,233: Unknown error initiating TCP/IP socket to 10.0.0.116:42504 (http://10.0.0.116:42545/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 364, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2017-10-18 07:51:06,234: topic[/state_command] removing connection to http://10.0.0.116:42545/
[rospy.internal][INFO] 2017-10-18 07:51:06,235: topic[/state_command] removing connection to http://10.0.0.116:42545/
[rospy.topics][ERROR] 2017-10-18 07:51:06,236: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][INFO] 2017-10-18 07:51:06,239: topic[/mavros/setpoint_raw/target_local] removing connection to http://10.0.0.116:45828/
[rospy.internal][WARNING] 2017-10-18 07:51:06,240: Unknown error initiating TCP/IP socket to 10.0.0.116:59484 (http://10.0.0.116:45828/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.impl.masterslave][INFO] 2017-10-18 07:51:06,242: signal-2
[rospy.core][INFO] 2017-10-18 07:51:06,720: signal_shutdown [atexit]
