[rospy.client][INFO] 2017-10-18 07:34:21,672: init_node, name[/state_avoiding_obstacle], pid[9272]
[xmlrpc][INFO] 2017-10-18 07:34:21,674: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2017-10-18 07:34:21,675: ROS Slave URI: [http://10.0.0.116:37700/]
[xmlrpc][INFO] 2017-10-18 07:34:21,676: Started XML-RPC server [http://10.0.0.116:37700/]
[rospy.impl.masterslave][INFO] 2017-10-18 07:34:21,676: _ready: http://10.0.0.116:37700/
[xmlrpc][INFO] 2017-10-18 07:34:21,677: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-10-18 07:34:21,679: Registering with master node http://10.0.0.116:11311
[rospy.init][INFO] 2017-10-18 07:34:21,776: registered with master
[rospy.rosout][INFO] 2017-10-18 07:34:21,777: initializing /rosout core topic
[rospy.rosout][INFO] 2017-10-18 07:34:21,786: connected to core topic /rosout
[rospy.simtime][INFO] 2017-10-18 07:34:21,803: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-10-18 07:34:21,898: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-10-18 07:34:21,914: topic[/state_command] adding connection to [http://10.0.0.116:37700/], count 0
[rospy.internal][INFO] 2017-10-18 07:34:21,927: topic[/state_command] adding connection to [/state_avoiding_obstacle], count 0
[rospy.internal][INFO] 2017-10-18 07:34:22,099: topic[/state_command] adding connection to [/state_follow_waypoint], count 1
[rospy.internal][INFO] 2017-10-18 07:34:22,130: topic[/state_command] adding connection to [http://10.0.0.116:45279/], count 1
[rospy.internal][INFO] 2017-10-18 07:34:22,347: topic[/state_command] adding connection to [/state_driving_to_cone], count 2
[rospy.internal][INFO] 2017-10-18 07:34:22,363: topic[/state_command] adding connection to [http://10.0.0.116:41716/], count 2
[rospy.internal][INFO] 2017-10-18 07:34:22,370: topic[/state_command] adding connection to [http://10.0.0.116:43611/], count 3
[rospy.internal][INFO] 2017-10-18 07:34:22,397: topic[/state_command] adding connection to [/state_driving_away], count 3
[rospy.internal][INFO] 2017-10-18 07:34:23,259: topic[/mavros/local_position/pose] adding connection to [http://10.0.0.116:34225/], count 0
[rospy.internal][INFO] 2017-10-18 07:34:23,305: topic[/mavros/setpoint_raw/target_local] adding connection to [http://10.0.0.116:34225/], count 0
[rospy.internal][INFO] 2017-10-18 07:34:23,342: topic[/mavros/state] adding connection to [http://10.0.0.116:34225/], count 0
[rospy.internal][INFO] 2017-10-18 07:34:23,407: topic[/mavros/battery] adding connection to [http://10.0.0.116:34225/], count 0
[rospy.internal][INFO] 2017-10-18 07:34:23,409: topic[/mavlink/from] adding connection to [http://10.0.0.116:34225/], count 0
[rospy.internal][INFO] 2017-10-18 07:34:23,627: topic[/mavros/mission/waypoints] adding connection to [http://10.0.0.116:34225/], count 0
[rospy.internal][INFO] 2017-10-18 07:34:23,698: topic[/exec_command] adding connection to [/exec], count 0
[rospy.internal][INFO] 2017-10-18 07:34:23,703: topic[/state_command] adding connection to [http://10.0.0.116:46044/], count 4
[rospy.internal][INFO] 2017-10-18 07:34:23,731: topic[/mavros/rc/override] adding connection to [/mavros], count 0
[rospy.core][INFO] 2017-10-18 07:35:11,626: signal_shutdown [signal-2]
[rospy.internal][ERROR] 2017-10-18 07:35:11,789: Unable to initiate TCP/IP socket to 10.0.0.116:33743 (http://10.0.0.116:43611/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:35:11,806: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-10-18 07:35:11,808: topic[/mavros/rc/override] removing connection to /mavros
[rospy.internal][INFO] 2017-10-18 07:35:11,810: topic[/state_command] removing connection to /state_avoiding_obstacle
[rospy.internal][ERROR] 2017-10-18 07:35:11,812: Unable to initiate TCP/IP socket to 10.0.0.116:46176 (http://10.0.0.116:37700/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:35:11,812: topic[/state_command] removing connection to /state_follow_waypoint
[rospy.internal][INFO] 2017-10-18 07:35:11,815: topic[/state_command] removing connection to /state_driving_to_cone
[rospy.internal][INFO] 2017-10-18 07:35:11,821: topic[/state_command] removing connection to /state_driving_away
[rospy.internal][INFO] 2017-10-18 07:35:11,826: topic[/exec_command] removing connection to /exec
[rospy.internal][INFO] 2017-10-18 07:35:11,831: topic[/mavros/mission/waypoints] removing connection to http://10.0.0.116:34225/
[rospy.internal][INFO] 2017-10-18 07:35:11,832: topic[/mavros/state] removing connection to http://10.0.0.116:34225/
[rospy.internal][INFO] 2017-10-18 07:35:11,832: topic[/mavlink/from] removing connection to http://10.0.0.116:34225/
[rospy.internal][INFO] 2017-10-18 07:35:11,834: topic[/mavros/local_position/pose] removing connection to http://10.0.0.116:34225/
[rospy.internal][INFO] 2017-10-18 07:35:11,839: topic[/mavros/battery] removing connection to http://10.0.0.116:34225/
[rospy.internal][ERROR] 2017-10-18 07:35:11,838: Unable to initiate TCP/IP socket to 10.0.0.116:44905 (http://10.0.0.116:45279/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:35:11,840: topic[/state_command] removing connection to http://10.0.0.116:37700/
[rospy.internal][INFO] 2017-10-18 07:35:11,841: topic[/state_command] removing connection to http://10.0.0.116:45279/
[rospy.internal][INFO] 2017-10-18 07:35:11,842: topic[/state_command] removing connection to http://10.0.0.116:41716/
[rospy.internal][INFO] 2017-10-18 07:35:11,843: topic[/state_command] removing connection to http://10.0.0.116:43611/
[rospy.internal][WARNING] 2017-10-18 07:35:11,836: Unknown error initiating TCP/IP socket to 10.0.0.116:49472 (http://10.0.0.116:34225/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
  File "/usr/lib/python2.7/socket.py", line 174, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

[rospy.internal][INFO] 2017-10-18 07:35:11,844: topic[/state_command] removing connection to http://10.0.0.116:46044/
[rospy.internal][INFO] 2017-10-18 07:35:11,846: topic[/mavros/setpoint_raw/target_local] removing connection to http://10.0.0.116:34225/
[rospy.internal][WARNING] 2017-10-18 07:35:11,847: Unknown error initiating TCP/IP socket to 10.0.0.116:33121 (http://10.0.0.116:41716/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.impl.masterslave][INFO] 2017-10-18 07:35:11,848: signal-2
[rospy.core][INFO] 2017-10-18 07:35:12,264: signal_shutdown [atexit]
