[rospy.client][INFO] 2017-10-18 07:34:21,817: init_node, name[/state_follow_waypoint], pid[9247]
[xmlrpc][INFO] 2017-10-18 07:34:21,818: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2017-10-18 07:34:21,827: ROS Slave URI: [http://10.0.0.116:45279/]
[xmlrpc][INFO] 2017-10-18 07:34:21,828: Started XML-RPC server [http://10.0.0.116:45279/]
[rospy.impl.masterslave][INFO] 2017-10-18 07:34:21,828: _ready: http://10.0.0.116:45279/
[xmlrpc][INFO] 2017-10-18 07:34:21,829: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-10-18 07:34:21,830: Registering with master node http://10.0.0.116:11311
[rospy.init][INFO] 2017-10-18 07:34:21,928: registered with master
[rospy.rosout][INFO] 2017-10-18 07:34:21,928: initializing /rosout core topic
[rospy.rosout][INFO] 2017-10-18 07:34:21,936: connected to core topic /rosout
[rospy.simtime][INFO] 2017-10-18 07:34:21,959: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-10-18 07:34:22,061: topic[/state_command] adding connection to [http://10.0.0.116:37700/], count 0
[rospy.internal][INFO] 2017-10-18 07:34:22,077: topic[/state_command] adding connection to [http://10.0.0.116:45279/], count 1
[rospy.internal][INFO] 2017-10-18 07:34:22,101: topic[/state_command] adding connection to [/state_follow_waypoint], count 0
[rospy.internal][INFO] 2017-10-18 07:34:22,133: topic[/state_command] adding connection to [/state_avoiding_obstacle], count 1
[rospy.internal][INFO] 2017-10-18 07:34:22,185: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-10-18 07:34:22,341: topic[/state_command] adding connection to [/state_driving_to_cone], count 2
[rospy.internal][INFO] 2017-10-18 07:34:22,356: topic[/state_command] adding connection to [http://10.0.0.116:41716/], count 2
[rospy.internal][INFO] 2017-10-18 07:34:22,372: topic[/state_command] adding connection to [http://10.0.0.116:43611/], count 3
[rospy.internal][INFO] 2017-10-18 07:34:22,401: topic[/state_command] adding connection to [/state_driving_away], count 3
[rospy.internal][INFO] 2017-10-18 07:34:23,087: topic[/mavros/local_position/pose] adding connection to [http://10.0.0.116:34225/], count 0
[rospy.internal][INFO] 2017-10-18 07:34:23,091: topic[/mavros/setpoint_raw/target_local] adding connection to [http://10.0.0.116:34225/], count 0
[rospy.internal][INFO] 2017-10-18 07:34:23,182: topic[/mavros/state] adding connection to [http://10.0.0.116:34225/], count 0
[rospy.internal][INFO] 2017-10-18 07:34:23,233: topic[/mavros/battery] adding connection to [http://10.0.0.116:34225/], count 0
[rospy.internal][INFO] 2017-10-18 07:34:23,234: topic[/mavlink/from] adding connection to [http://10.0.0.116:34225/], count 0
[rospy.internal][INFO] 2017-10-18 07:34:23,519: topic[/mavros/mission/waypoints] adding connection to [http://10.0.0.116:34225/], count 0
[rospy.internal][INFO] 2017-10-18 07:34:23,613: topic[/mavros/rc/override] adding connection to [/mavros], count 0
[rospy.internal][INFO] 2017-10-18 07:34:23,707: topic[/exec_command] adding connection to [/exec], count 0
[rospy.internal][INFO] 2017-10-18 07:34:23,717: topic[/state_command] adding connection to [http://10.0.0.116:46044/], count 4
[rospy.core][INFO] 2017-10-18 07:35:11,647: signal_shutdown [signal-2]
[rospy.internal][ERROR] 2017-10-18 07:35:11,802: Unable to initiate TCP/IP socket to 10.0.0.116:33743 (http://10.0.0.116:43611/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-10-18 07:35:11,814: Unable to initiate TCP/IP socket to 10.0.0.116:46176 (http://10.0.0.116:37700/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:35:11,825: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-10-18 07:35:11,826: topic[/mavros/rc/override] removing connection to /mavros
[rospy.internal][INFO] 2017-10-18 07:35:11,827: topic[/state_command] removing connection to /state_follow_waypoint
[rospy.internal][INFO] 2017-10-18 07:35:11,828: topic[/state_command] removing connection to /state_avoiding_obstacle
[rospy.internal][INFO] 2017-10-18 07:35:11,830: topic[/state_command] removing connection to /state_driving_to_cone
[rospy.internal][INFO] 2017-10-18 07:35:11,832: topic[/state_command] removing connection to /state_driving_away
[rospy.internal][INFO] 2017-10-18 07:35:11,834: topic[/exec_command] removing connection to /exec
[rospy.internal][INFO] 2017-10-18 07:35:11,837: topic[/mavros/mission/waypoints] removing connection to http://10.0.0.116:34225/
[rospy.internal][INFO] 2017-10-18 07:35:11,838: topic[/mavros/state] removing connection to http://10.0.0.116:34225/
[rospy.internal][ERROR] 2017-10-18 07:35:11,835: Unable to initiate TCP/IP socket to 10.0.0.116:44905 (http://10.0.0.116:45279/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:35:11,839: topic[/mavlink/from] removing connection to http://10.0.0.116:34225/
[rospy.internal][INFO] 2017-10-18 07:35:11,841: topic[/mavros/local_position/pose] removing connection to http://10.0.0.116:34225/
[rospy.internal][INFO] 2017-10-18 07:35:11,842: topic[/mavros/battery] removing connection to http://10.0.0.116:34225/
[rospy.internal][INFO] 2017-10-18 07:35:11,843: topic[/state_command] removing connection to http://10.0.0.116:37700/
[rospy.internal][INFO] 2017-10-18 07:35:11,844: topic[/state_command] removing connection to http://10.0.0.116:45279/
[rospy.internal][INFO] 2017-10-18 07:35:11,844: topic[/state_command] removing connection to http://10.0.0.116:41716/
[rospy.internal][WARNING] 2017-10-18 07:35:11,845: Unknown error initiating TCP/IP socket to 10.0.0.116:49472 (http://10.0.0.116:34225/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][INFO] 2017-10-18 07:35:11,846: topic[/state_command] removing connection to http://10.0.0.116:43611/
[rospy.internal][INFO] 2017-10-18 07:35:11,847: topic[/state_command] removing connection to http://10.0.0.116:46044/
[rospy.internal][INFO] 2017-10-18 07:35:11,848: topic[/mavros/setpoint_raw/target_local] removing connection to http://10.0.0.116:34225/
[rospy.internal][WARNING] 2017-10-18 07:35:11,849: Unknown error initiating TCP/IP socket to 10.0.0.116:49472 (http://10.0.0.116:34225/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.topics][ERROR] 2017-10-18 07:35:11,851: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.impl.masterslave][INFO] 2017-10-18 07:35:11,851: signal-2
[rospy.core][INFO] 2017-10-18 07:35:12,273: signal_shutdown [atexit]
